### PR TITLE
add /income/get

### LINKED ISSUE #79: income/get
Hi,
Is there a reason why the api endpoint "income/get" is not included ? How should I proceed if I want to include the endpoint in the code ?

### PR DESCRIPTION
**Pull request by michaelckelly**
Fixes #79

### CODE REVIEW

**Comment by dustinconrad** [comment]
@michaelckelly the income enumeration value is also commented out of the product enumeration, 

```
public enum Product {
  @SerializedName("balance") BALANCE,
  @SerializedName("credit_details") CREDIT_DETAILS,
  //  @SerializedName("income") INCOME,
  @SerializedName("identity") IDENTITY,
  @SerializedName("auth") AUTH,
  //  @SerializedName("risk") RISK
  @SerializedName("transactions") TRANSACTIONS,
}
```

**Comment by michaelckelly** [comment]
@dustinconrad What file are you seeing that? I am looking at https://github.com/plaid/plaid-java/blob/6586e6b21dbd68c3c308ddd7687fa26e7a3c21bd/src/main/java/com/plaid/client/request/common/Product.java#L8

**Comment by dustinconrad** [comment]
@michaelckelly Apologies, you are correct.

I was looking at an old version of the file.  Sorry for the false alarm.

**Comment by dustinconrad** [comment]
@michaelckelly Sorry, I was looking at an older version of the file.  You are correct, that enumeration is now present.

**Comment by michaelckelly** [comment]
No worries @dustinconrad - you have flagged plenty of legit issues so far! :) Tests are passing now so as soon as this is reviewed we'll get this as well as #82 and #83 out in a release.

**Pull request merged**
