### PR TITLE
Stripe bank account token

### PR DESCRIPTION
**Pull request by gkatalevsky**

### CODE REVIEW

**Comment by anzecesar** [comment]
👍

**Comment by ob-stripe** [comment]
@erimag Sorry to ping you directly, but do you think it would be possible to merge this in? Without this, Stripe+Plaid Link users are forced to manually issue requests to Plaid's API without using the bindings.

**Comment by erimag** [comment]
@ob-stripe Thanks for pinging me, somehow my notifications were turned off so that was good! Will try to look at it asap.

**Comment by gkatalevsky** [comment]
@erimag thanks for merging it in. Could you please also roll out the new version with these changes included?

**Comment by erimag** [comment]
@gkatalevsky Sure thing. Scheduling new maven release for later today.

**Comment by supriya-promise** [comment]
@gkatalevsky  Thanks for your contribution!
@erimag  Thanks for scheduling the maven release, I'm looking forward to pulling in the maven release. Do you have rough time estimates on when it would be released?

**Comment by jjshammas** [comment]
@erimag Waiting on this release in order to use exchangeToken with an account ID. Any timeframe?

**Comment by barrymazza** [comment]
@erimag Any ETA on getting this into a maven release?

**Comment by erimag** [comment]
Hey, sorry. Will try to get it out the door by tomorrow at the latest!

**Comment by erimag** [comment]
@barrymazza @jjshammas Released plaid-java version 0.3.2 to Sonatype OSS Repository for synching to Maven Central, should be available for Maven consumption within the next 12 hours.

**Comment by ob-stripe** [comment]
Awesome, thanks for the release @erimag! And happy new year :)

**Pull request merged**
